/** @type {import('tailwindcss').Config} */
export default {
	darkMode: ["class"],
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		extend: {
			borderRadius: {
				DEFAULT: "0.25rem",
				lg: "0.5rem",
				xl: "0.75rem",
				full: "9999px",
			},
			colors: {
				// Melodix Design System - Full M3 Color Tokens
				"on-secondary-fixed": "#1b1c1c",
				"on-secondary-container": "#b7b5b4",
				"error-container": "#93000a",
				"primary-fixed": "#72fe8f",
				"on-error": "#690005",
				"surface-dim": "#131313",
				"surface-container": "#201f1f",
				"surface-container-low": "#1c1b1b",
				surface: "#131313",
				"inverse-primary": "#006e2d",
				error: "#ffb4ab",
				"on-primary-fixed-variant": "#005320",
				"primary-fixed-dim": "#53e076",
				"surface-bright": "#393939",
				"secondary-fixed": "#e5e2e1",
				"inverse-on-surface": "#313030",
				background: "#131313",
				"on-tertiary-fixed": "#1b1c1c",
				outline: "#869585",
				tertiary: "#c8c6c6",
				"on-background": "#e5e2e1",
				"tertiary-container": "#a2a1a1",
				"surface-container-lowest": "#0e0e0e",
				"surface-variant": "#353534",
				"on-primary-container": "#004118",
				"on-tertiary-container": "#383838",
				"on-surface": "#e5e2e1",
				primary: "#53e076",
				"on-surface-variant": "#bccbb9",
				"secondary-fixed-dim": "#c8c6c5",
				"surface-container-highest": "#353534",
				"inverse-surface": "#e5e2e1",
				"on-tertiary-fixed-variant": "#474747",
				"on-tertiary": "#303030",
				"surface-tint": "#53e076",
				"surface-container-high": "#2a2a2a",
				"on-primary": "#003914",
				"on-primary-fixed": "#002108",
				"tertiary-fixed-dim": "#c8c6c6",
				"secondary-container": "#474746",
				"outline-variant": "#3d4a3d",
				"on-error-container": "#ffdad6",
				"tertiary-fixed": "#e4e2e2",
				"primary-container": "#1db954",
				"on-secondary": "#303030",
				"on-secondary-fixed-variant": "#474746",
				secondary: "#c8c6c5",

				// ShadCN compat tokens
				foreground: "#e5e2e1",
				card: {
					DEFAULT: "#201f1f",
					foreground: "#e5e2e1",
				},
				popover: {
					DEFAULT: "#131313",
					foreground: "#e5e2e1",
				},
				muted: {
					DEFAULT: "#1c1b1b",
					foreground: "#bccbb9",
				},
				accent: {
					DEFAULT: "#1c1b1b",
					foreground: "#e5e2e1",
				},
				destructive: {
					DEFAULT: "#93000a",
					foreground: "#ffdad6",
				},
				border: "#3d4a3d",
				input: "#353534",
				ring: "#53e076",
			},
			spacing: {
				lg: "24px",
				xl: "32px",
				"margin-desktop": "32px",
				sm: "8px",
				unit: "8px",
				gutter: "24px",
				xs: "4px",
				"margin-mobile": "16px",
				md: "16px",
			},
			fontFamily: {
				"body-sm": ["Inter"],
				"body-lg": ["Plus Jakarta Sans"],
				"title-md": ["Plus Jakarta Sans"],
				"headline-lg-mobile": ["Plus Jakarta Sans"],
				"display-lg": ["Plus Jakarta Sans"],
				"headline-lg": ["Plus Jakarta Sans"],
				"label-md": ["Inter"],
				sans: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
			},
			fontSize: {
				"body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
				"body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
				"title-md": [
					"20px",
					{ lineHeight: "28px", fontWeight: "700" },
				],
				"headline-lg-mobile": [
					"24px",
					{ lineHeight: "32px", fontWeight: "700" },
				],
				"display-lg": [
					"48px",
					{
						lineHeight: "56px",
						letterSpacing: "-0.02em",
						fontWeight: "800",
					},
				],
				"headline-lg": [
					"32px",
					{
						lineHeight: "40px",
						letterSpacing: "-0.01em",
						fontWeight: "700",
					},
				],
				"label-md": [
					"12px",
					{
						lineHeight: "16px",
						letterSpacing: "0.05em",
						fontWeight: "600",
					},
				],
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
};
